package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/dolthub/dolt/go/libraries/doltcore/servercfg"
	"github.com/dolthub/dolt/go/libraries/utils/filesys"
	"gopkg.in/yaml.v3"

	"github.com/steveyegge/beads/internal/config"
	"github.com/steveyegge/beads/internal/configfile"
	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/storage/db/proxy"
	"github.com/steveyegge/beads/internal/storage/dolt"
	proxieddolt "github.com/steveyegge/beads/internal/storage/doltserver"
)

// Filesystem layout for --proxied-server (per workspace, all under one dir):
//
//	<beadsDir>/proxieddb/                       proxy lockfile, pidfile,
//	                                            child dolt repository
//	<beadsDir>/proxieddb/server_config.yaml     dolt sql-server YAML
//	                                            (host / port / log_level)
//	<beadsDir>/proxieddb/server.log             daemon stdout/stderr
//
// The whole directory is owned by the per-workspace proxied dolt sql-server
// feature and is gitignored.
//
// server_config.yaml is auto-generated by ensureProxiedServerConfig — UNLESS
// the caller has configured a custom path via BEADS_PROXIED_SERVER_CONFIG
// or metadata.json's dolt_proxied_server_config (set by `bd init
// --server-config <path>`). In that case bd validates the user-supplied
// file but never auto-creates one; the user owns its lifecycle.
const (
	proxiedServerRootName   = "proxieddb"
	proxiedServerConfigName = "server_config.yaml"
	proxiedServerLogName    = "server.log"
)

func proxiedServerRoot(beadsDir string) string {
	return filepath.Join(beadsDir, proxiedServerRootName)
}

func proxiedServerConfigPath(beadsDir string) string {
	return filepath.Join(proxiedServerRoot(beadsDir), proxiedServerConfigName)
}

func proxiedServerLogPath(beadsDir string) string {
	return filepath.Join(proxiedServerRoot(beadsDir), proxiedServerLogName)
}

// resolveProxiedServerConfigPath returns the dolt sql-server YAML path the
// proxied-server backend should use, plus a flag indicating whether the path
// is user-supplied (custom) or bd's default.
//
// Resolution chain:
//  1. BEADS_PROXIED_SERVER_CONFIG env var (highest; absolute paths welcome).
//  2. metadata.json's dolt_proxied_server_config field (relative to beadsDir).
//  3. The default <beadsDir>/proxieddb/server_config.yaml.
//
// Steps 1+2 collapse into cfg.GetDoltProxiedServerConfig (configfile owns
// the env-var name in one place); cfg may be nil here, e.g. when init runs
// before metadata.json has been written — we substitute an empty Config so
// the env-var check still happens.
//
// isCustom == true means "the user owns this file": callers must not
// auto-create it, and bd validates it exists rather than writing one.
func resolveProxiedServerConfigPath(beadsDir string, cfg *configfile.Config) (path string, isCustom bool) {
	if cfg == nil {
		cfg = &configfile.Config{}
	}
	if custom := cfg.GetDoltProxiedServerConfig(beadsDir); custom != "" {
		return custom, true
	}
	return proxiedServerConfigPath(beadsDir), false
}

// ensureProxiedServerConfig resolves the proxied dolt sql-server YAML path
// and guarantees a usable file is on disk, returning the path. Two modes:
//
//   - Default location (no override configured): mkdir the proxieddb root if
//     missing, write a freshly-rendered YAML with a free port baked in if
//     the file is missing, then return. The picked port is sticky across
//     bd invocations to keep the running daemon's listener stable.
//
//   - Custom location (BEADS_PROXIED_SERVER_CONFIG env or
//     metadata.json's dolt_proxied_server_config): the user owns the file.
//     bd never auto-creates it. We validate that it exists, is a regular
//     file, and parses through dolt's own loader — failing fast at config
//     time rather than at daemon-spawn time.
//
// cfg may be nil when init runs before metadata.json is on disk; the env
// var is still honored in that case.
func ensureProxiedServerConfig(beadsDir string, cfg *configfile.Config) (string, error) {
	path, isCustom := resolveProxiedServerConfigPath(beadsDir, cfg)

	if isCustom {
		info, err := os.Stat(path)
		if err != nil {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: %w", path, err)
		}
		if !info.Mode().IsRegular() {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: not a regular file", path)
		}
		if _, err := servercfg.YamlConfigFromFile(filesys.LocalFS, path); err != nil {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: parse: %w", path, err)
		}
		return path, nil
	}

	root := proxiedServerRoot(beadsDir)
	if err := os.MkdirAll(root, config.BeadsDirPerm); err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: mkdir %s: %w", root, err)
	}

	switch _, err := os.Stat(path); {
	case err == nil:
		return path, nil
	case !os.IsNotExist(err):
		return "", fmt.Errorf("ensureProxiedServerConfig: stat %s: %w", path, err)
	}

	port, err := proxy.PickFreePort()
	if err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: pick free port: %w", err)
	}

	body, err := renderProxiedServerConfig(port)
	if err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: render YAML: %w", err)
	}
	if err := os.WriteFile(path, body, 0o600); err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: write %s: %w", path, err)
	}
	return path, nil
}

// validateProxiedServerConfig enforces the contract --server-config carries:
// the path must exist, be a regular file, and parse via dolt's own
// servercfg loader. Init invokes this before any side effects so a bad
// config aborts the run with a clear message rather than failing later
// when the daemon tries to spawn against it.
func validateProxiedServerConfig(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("--server-config %s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("--server-config %s: not a regular file", path)
	}
	if _, err := servercfg.YamlConfigFromFile(filesys.LocalFS, path); err != nil {
		return fmt.Errorf("--server-config %s: parse: %w", path, err)
	}
	return nil
}

func renderProxiedServerConfig(port int) ([]byte, error) {
	host := proxiedServerListenerHost
	logLevel := string(servercfg.LogLevel_Info)
	yc := &servercfg.YAMLConfig{
		LogLevelStr: &logLevel,
		ListenerConfig: servercfg.ListenerYAMLConfig{
			HostStr:    &host,
			PortNumber: &port,
		},
	}
	return yaml.Marshal(yc)
}

const proxiedServerListenerHost = "127.0.0.1"

func newProxiedServerStore(ctx context.Context, cfg *dolt.Config) (storage.DoltStorage, error) {
	if cfg == nil {
		return nil, fmt.Errorf("newProxiedServerStore: cfg is nil")
	}
	if cfg.BeadsDir == "" {
		return nil, fmt.Errorf("newProxiedServerStore: cfg.BeadsDir must be set")
	}
	if cfg.Database == "" {
		return nil, fmt.Errorf("newProxiedServerStore: cfg.Database must be set")
	}

	doltBin, err := exec.LookPath("dolt")
	if err != nil {
		return nil, fmt.Errorf("newProxiedServerStore: dolt is not installed (not found in PATH); install from https://docs.dolthub.com/introduction/installation: %w", err)
	}

	// Best-effort: metadata.json carries the configured dolt_proxied_server_config
	// override (if any). At init time the file may not exist yet — pass nil
	// in that case and let resolveProxiedServerConfigPath fall through to env
	// var or default.
	persisted, _ := configfile.Load(cfg.BeadsDir)

	configPath, err := ensureProxiedServerConfig(cfg.BeadsDir, persisted)
	if err != nil {
		return nil, err
	}

	name, email := cfg.CommitterName, cfg.CommitterEmail
	if name == "" || email == "" {
		fallbackName, fallbackEmail := proxiedServerCommitter()
		if name == "" {
			name = fallbackName
		}
		if email == "" {
			email = fallbackEmail
		}
	}

	return proxieddolt.NewDoltServerStore(
		ctx,
		proxiedServerRoot(cfg.BeadsDir),
		cfg.BeadsDir,
		cfg.Database,
		name, email,
		proxiedServerLogPath(cfg.BeadsDir),
		configPath,
		proxy.BackendLocalServer,
		false, // autoSyncToOriginRemote — wired in a future iteration
		"root",
		"", // rootPassword: proxy is loopback-only, no auth
		doltBin,
	)
}

func proxiedServerCommitter() (string, string) {
	name, email := "beads", "beads@localhost"
	if out, err := exec.Command("git", "config", "user.name").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			name = v
		}
	}
	if out, err := exec.Command("git", "config", "user.email").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			email = v
		}
	}
	return name, email
}
